"""
Dicts and lists used in Cronometer json files
For salt, multiply by grams by 400 and add is as mg sodium.
"""

# Nutrients names used in Ciqual table
NUTRIENTS_ID = {
    "Protéines, N x facteur de Jones": 203,
    "Lipides": 204,
    "Glucides": 205,
    "Cendres": 207,
    "Energie, N x facteur Jones, avec fibres": 208,
    "Amidon": 209,
    "Saccharose": 210,
    "Glucose": 211,
    "Fructose": 212,
    "Lactose": 213,
    "Maltose": 214,
    "Alcool": 221,
    "Eau": 255,
    "Sucres": 269,
    "Galactose": 287,
    "Fibres alimentaires": 291,
    "Calcium": 301,
    "Fer": 303,
    "Magnesium": 304,
    "Phosphore": 305,
    "Potassium": 306,
    "Sodium": 307,
    "Zinc": 309,
    "Cuivre": 312,
    "Manganèse": 315,
    "Sélènium": 317,
    "Vitamine A": 320,
    "Rétinol": 319,
    "Beta-carotène": 321,
    "Vitamine E": 323,
    "Vitamine D": 324,
    "Vitamine C": 401,
    "Vitamine B1 ou Thiamine": 404,
    "Vitamine B2 ou Riboflavine": 405,
    "Vitamine B3 ou PP ou Niacine": 406,
    "Vitamine B5 ou Acide pantothénique": 410,
    "Vitamine B6": 415,
    "Vitamine B9 ou Folates totaux": 417,
    "Vitamine B12": 418,
    "Vitamin K": 430,
    "Cholestérol": 601,
    "AG saturés": 606,
    "AG monoinsaturés": 645,
    "AG polyinsaturés": 646,
    "Omega-3": 10001,
    "Omega-6": 10002,
    "Iode": 10005
}

SSGRP_CATEGORIES = {
    # ssgrp
    'salades composées et crudités': 14,
    'soupes': 21,
    'pizzas, tartes et crêpes salées': 14,
    'sandwichs': 14,
    'feuilletées et autres entrées': 14,
    'pommes de terre et autres tubercules': 25,
    'fruits à coque et graines oléagineuses': 15,
    'biscuits apéritifs': 20,
    'charcuteries et assimilés': 19,
    'autres produits à base de viande': 19,
    'poissons cuits': 10,
    'poissons crus': 10,
    'mollusques et crustacés cuits': 10,
    'mollusques et crustacés crus': 10,
    'produits à base de poissons et produits de la mer': 10,
    'substitus de produits carnés': 13,
    'fromages et assimilés': 7,
    'crèmes et spécialités à base de crème': 7,
    'eaux': 4,
    'sucres, miels et assimilés': 24,
    'chocolats et produits à base de chocolat': 24,
    'confiseries non chocolatées': 24,
    'confitures et assimilés': 24,
    'viennoiseries': 2,
    'biscuits sucrés': 2,
    'céréales de petit-déjeuner': 5,
    'barres céréalières': 5,
    'gâteaux et pâtisseries': 24,
    'glaces': 7,
    'sorbets': 7,
    'desserts glacés': 7,
    'beurres': 9,
    'huiles et graisses végétales': 9,
    'margarines': 9,
    'huiles de poissons': 9,
    'autres matières grasses': 9,
    'sauces': 21,
    'condiments': 22,
    'aides culinaires': 22,
    'sels': 22,
    'épices': 22,
    'algues': 25,
    'denrées destinées à une alimentation particulière': 23,
    'aides culinaires et ingrédients pour végétariens': 23,
    'ingrédients divers': 23,
    'laits et boissons infantiles': 1,
    'petits pots salés et plats infantiles': 1,
    'desserts infantiles': 1,
    'céréales et biscuits infantiles': 1,
    # ssssgrp
    'plats de viande sans garniture': 14,
    'plats de viande et féculents': 14,
    'plats de viande et légumes/légumineuses': 14,
    'plats de poisson sans garniture': 10,
    'plats de poisson et féculents': 10,
    'plats de légumes/légumineuses': 25,
    'plats de céréales/pâtes': 6,
    'plats de fromage': 7,
    'plats végétariens': 14,
    'légumes crus': 25,
    'légumes cuits': 25,
    'légumes séchés ou déshydratés': 25,
    'légumes et leurs produits de la Martinique': 25,
    'légumes et leurs produits de la Réunion': 25,
    'légumineuses cuites': 13,
    'légumineuses fraîches': 13,
    'légumineuses sèches': 13,
    'fruits crus': 11,
    'compotes et assimilés': 11,
    'fruits appertisés': 11,
    'fruits séchés': 11,
    'fruits et leurs produits de la Martinique': 11,
    'fruits et leurs produits de la Réunion': 11,
    'pâtes, riz et céréales cuits': 6,
    'pâtes, riz et céréales crus': 6,
    'pains': 2,
    'biscottes et pains grillés': 2,
    'bœuf et veau': 3,
    'porc': 16,
    'poulet': 17,
    'dinde': 17,
    'agneau et mouton': 12,
    'gibier': 12,
    'autres viandes': 19,
    'abats': 19,
    'jambons cuits': 19,
    'jambons secs et crus': 19,
    'saucisson secs': 19,
    'saucisses et assimilés': 19,
    'pâtés et terrines': 19,
    'rillettes': 19,
    'quenelles': 10,
    'autres spécialités charcutières': 19,
    'substituts de charcuteries pour végétariens': 25,
    'œufs cuits': 7,
    'œufs crus': 7,
    'omelettes et autres ovoproduits': 7,
    'laits de vaches liquides (non concentrés)': 7,
    'laits autres que de vache': 7,
    'laits de vache concentrés ou en poudre': 7,
    'yaourts et spécialités laitières type yaourt': 7,
    'fromages blancs': 7,
    'desserts lactés': 7,
    'autres desserts': 7,
    'desserts végétaux': 25,
    'fromages à pâte molle': 7,
    'fromages à pâte persillée': 7,
    'fromages à pâte pressée': 7,
    'fromage fondus': 7,
    'autres fromages et spécialités': 7,
    'substituts de fromages pour végétariens': 25,
    'jus': 4,
    'nectars': 4,
    'boissons rafraîchissantes sans alcool': 4,
    'boissons rafraîchissantes lactées': 4,
    'boissons végétales': 4,
    'café: , thé: , cacao etc. prêts à consommer': 4,
    'boissons à reconstituer': 4,
    'vins': 4,
    'bières et cidres': 4,
    'liqueurs et alcools': 4,
    'cocktails': 4,
    'sauces condimentaires': 21,
    'sauces chaudes': 21,
    'sauces sucrées': 21,
    'herbes fraîches': 22,
    'herbes séchées': 22
}

LANGUAGES = {
    "en": 20829061,
    "fr": 20829062,
    "es": 20829063,
    "de": 20829064,
    "it": 20829065,
    "pl": 20829066,
}