"""
Dicts and lists used in Cronometer json files
For salt, multiply by grams by 400 and add is as mg sodium.
"""

# Nutrients names used in Ciqual table
NUTRIENTS_ID = {
    "Protéines, N x facteur de Jones (g/100 g)": 203,
    "Lipides (g/100 g)": 204,
    "Glucides (g/100 g)": 205,
    "Cendres (g/100 g)": 207,
    "Energie, N x facteur Jones, avec fibres": 208,
    "Amidon (g/100 g)": 209,
    "Saccharose (g/100 g)": 210,
    "Glucose (g/100 g)": 211,
    "Fructose (g/100 g)": 212,
    "Lactose (g/100 g)": 213,
    "Maltose (g/100 g)": 214,
    "Alcool (g/100 g)": 221,
    "Eau (g/100 g)": 255,
    "Sucres (g/100 g)": 269,
    "Galactose (g/100 g)": 287,
    "Fibres alimentaires (g/100 g)": 291,
    "Calcium (mg/100 g)": 301,
    "Fer (mg/100 g)": 303,
    "Magnésium (mg/100 g)": 304,
    "Phosphore (mg/100 g)": 305,
    "Potassium (mg/100 g)": 306,
    "Sodium (mg/100 g)": 307,
    "Zinc (mg/100 g)": 309,
    "Cuivre (mg/100 g)": 312,
    "Manganèse (mg/100 g)": 315,
    "Sélénium (µg/100 g)": 317,
    "Vitamine A": 320,
    "Rétinol (µg/100 g)": 319,
    "Beta-Carotène (µg/100 g)": 321,
    "Vitamine E (mg/100 g)": 323,
    "Vitamine D (µg/100 g)": 324,
    "Vitamine C (mg/100 g)": 401,
    "Vitamine B1 ou Thiamine (mg/100 g)": 404,
    "Vitamine B2 ou Riboflavine (mg/100 g)": 405,
    "Vitamine B3 ou PP ou Niacine (mg/100 g)": 406,
    "Vitamine B5 ou Acide pantothénique (mg/100 g)": 410,
    "Vitamine B6 (mg/100 g)": 415,
    "Vitamine B9 ou Folates totaux (µg/100 g)": 417,
    "Vitamine B12 (µg/100 g)": 418,
    "Vitamine K": 430,
    "Cholestérol (mg/100 g)": 601,
    "AG saturés (g/100 g)": 606,
    "AG monoinsaturés (g/100 g)": 645,
    "AG polyinsaturés (g/100 g)": 646,
    "Omega-3": 10001,
    "Omega-6": 10002,
    "Iode (µg/100 g)": 10005
}

SSGRP_CATEGORIES = {
    # ssgrp
    'salades composées et crudités': 14,
    'soupes': 21,
    'pizzas, tartes et crêpes salées': 14,
    'sandwichs': 14,
    'feuilletées et autres entrées': 14,
    'pommes de terre et autres tubercules': 25,
    'fruits à coque et graines oléagineuses': 15,
    'biscuits apéritifs': 20,
    'charcuteries et assimilés': 19,
    'autres produits à base de viande': 19,
    'poissons cuits': 10,
    'poissons crus': 10,
    'mollusques et crustacés cuits': 10,
    'mollusques et crustacés crus': 10,
    'produits à base de poissons et produits de la mer': 10,
    'substitus de produits carnés': 13,
    'fromages et assimilés': 7,
    'crèmes et spécialités à base de crème': 7,
    'eaux': 4,
    'sucres, miels et assimilés': 24,
    'chocolats et produits à base de chocolat': 24,
    'confiseries non chocolatées': 24,
    'confitures et assimilés': 24,
    'viennoiseries': 2,
    'biscuits sucrés': 2,
    'céréales de petit-déjeuner': 5,
    'barres céréalières': 5,
    'gâteaux et pâtisseries': 24,
    'glaces': 7,
    'sorbets': 7,
    'desserts glacés': 7,
    'beurres': 9,
    'huiles et graisses végétales': 9,
    'margarines': 9,
    'huiles de poissons': 9,
    'autres matières grasses': 9,
    'sauces': 21,
    'condiments': 22,
    'aides culinaires': 22,
    'sels': 22,
    'épices': 22,
    'algues': 25,
    'denrées destinées à une alimentation particulière': 23,
    'aides culinaires et ingrédients pour végétariens': 23,
    'ingrédients divers': 23,
    'laits et boissons infantiles': 1,
    'petits pots salés et plats infantiles': 1,
    'desserts infantiles': 1,
    'céréales et biscuits infantiles': 1,
    # ssssgrp
    'plats de viande sans garniture': 14,
    'plats de viande et féculents': 14,
    'plats de viande et légumes/légumineuses': 14,
    'plats de poisson sans garniture': 10,
    'plats de poisson et féculents': 10,
    'plats de légumes/légumineuses': 25,
    'plats de céréales/pâtes': 6,
    'plats de fromage': 7,
    'plats végétariens': 14,
    'légumes crus': 25,
    'légumes cuits': 25,
    'légumes séchés ou déshydratés': 25,
    'légumes et leurs produits de la Martinique': 25,
    'légumes et leurs produits de la Réunion': 25,
    'légumineuses cuites': 13,
    'légumineuses fraîches': 13,
    'légumineuses sèches': 13,
    'fruits crus': 11,
    'compotes et assimilés': 11,
    'fruits appertisés': 11,
    'fruits séchés': 11,
    'fruits et leurs produits de la Martinique': 11,
    'fruits et leurs produits de la Réunion': 11,
    'pâtes, riz et céréales cuits': 6,
    'pâtes, riz et céréales crus': 6,
    'pains': 2,
    'biscottes et pains grillés': 2,
    'bœuf et veau': 3,
    'porc': 16,
    'poulet': 17,
    'dinde': 17,
    'agneau et mouton': 12,
    'gibier': 12,
    'autres viandes': 19,
    'abats': 19,
    'jambons cuits': 19,
    'jambons secs et crus': 19,
    'saucisson secs': 19,
    'saucisses et assimilés': 19,
    'pâtés et terrines': 19,
    'rillettes': 19,
    'quenelles': 10,
    'autres spécialités charcutières': 19,
    'substituts de charcuteries pour végétariens': 25,
    'œufs cuits': 7,
    'œufs crus': 7,
    'omelettes et autres ovoproduits': 7,
    'laits de vaches liquides (non concentrés)': 7,
    'laits autres que de vache': 7,
    'laits de vache concentrés ou en poudre': 7,
    'yaourts et spécialités laitières type yaourt': 7,
    'fromages blancs': 7,
    'desserts lactés': 7,
    'autres desserts': 7,
    'desserts végétaux': 25,
    'fromages à pâte molle': 7,
    'fromages à pâte persillée': 7,
    'fromages à pâte pressée': 7,
    'fromage fondus': 7,
    'autres fromages et spécialités': 7,
    'substituts de fromages pour végétariens': 25,
    'jus': 4,
    'nectars': 4,
    'boissons rafraîchissantes sans alcool': 4,
    'boissons rafraîchissantes lactées': 4,
    'boissons végétales': 4,
    'café: , thé: , cacao etc. prêts à consommer': 4,
    'boissons à reconstituer': 4,
    'vins': 4,
    'bières et cidres': 4,
    'liqueurs et alcools': 4,
    'cocktails': 4,
    'sauces condimentaires': 21,
    'sauces chaudes': 21,
    'sauces sucrées': 21,
    'herbes fraîches': 22,
    'herbes séchées': 22
}

LANGUAGES = {
    "en": 20829061,
    "fr": 20829062,
    "es": 20829063,
    "de": 20829064,
    "it": 20829065,
    "pl": 20829066,
}